FROM golang:1.22.1 as builder
WORKDIR /app
RUN git clone https://github.com/pressly/goose.git goose-master

RUN cd goose-master && CGO_ENABLED=0 go build -tags='no_mysql no_sqlite3 no_mssql no_redshift no_tidb no_clickhouse no_vertica no_ydb' -o /app/goose ./cmd/goose
RUN chmod +x /app/goose

FROM gcr.io/distroless/static-debian12:nonroot

COPY ./migrations /migrations
COPY --from=builder /app/goose /

ENV GOOSE_DRIVER=postgres
ENV GOOSE_MIGRATION_DIR=/migrations

ENTRYPOINT ["/goose", "up"]
